// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyUserPermissions = `-- name: ApplyUserPermissions :one
INSERT INTO user_permissions (user_id, revision, permissions)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET
    revision = EXCLUDED.revision,
    permissions = EXCLUDED.permissions,
    updated_at = now()
WHERE user_permissions.revision < EXCLUDED.revision
RETURNING user_id
`

type ApplyUserPermissionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Revision    int64     `json:"revision"`
	Permissions []string  `json:"permissions"`
}

func (q *Queries) ApplyUserPermissions(ctx context.Context, arg ApplyUserPermissionsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, applyUserPermissions, arg.UserID, arg.Revision, arg.Permissions)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const completeUserImportEntry = `-- name: CompleteUserImportEntry :exec
UPDATE user_import_entries
SET state = 'completed'
WHERE import_id = $1 AND user_id = $2 AND state = 'pending'
`

type CompleteUserImportEntryParams struct {
	ImportID uuid.UUID `json:"import_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CompleteUserImportEntry(ctx context.Context, arg CompleteUserImportEntryParams) error {
	_, err := q.db.Exec(ctx, completeUserImportEntry, arg.ImportID, arg.UserID)
	return err
}

const createImportedUser = `-- name: CreateImportedUser :one
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreateImportedUserParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) CreateImportedUser(ctx context.Context, arg CreateImportedUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createImportedUser, arg.ID, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type CreateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const createUserImport = `-- name: CreateUserImport :one
INSERT INTO user_imports (id, total_count, correlation_id)
VALUES ($1, $2, $3)
RETURNING id, state, total_count, completed_count, failed_count, created_at, started_at, finished_at, correlation_id
`

type CreateUserImportParams struct {
	ID            uuid.UUID `json:"id"`
	TotalCount    int32     `json:"total_count"`
	CorrelationID string    `json:"correlation_id"`
}

func (q *Queries) CreateUserImport(ctx context.Context, arg CreateUserImportParams) (UserImport, error) {
	row := q.db.QueryRow(ctx, createUserImport, arg.ID, arg.TotalCount, arg.CorrelationID)
	var i UserImport
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.TotalCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CorrelationID,
	)
	return i, err
}

const createUserImportEntry = `-- name: CreateUserImportEntry :exec
INSERT INTO user_import_entries (import_id, user_id, email)
VALUES ($1, $2, $3)
`

type CreateUserImportEntryParams struct {
	ImportID uuid.UUID `json:"import_id"`
	UserID   uuid.UUID `json:"user_id"`
	Email    string    `json:"email"`
}

func (q *Queries) CreateUserImportEntry(ctx context.Context, arg CreateUserImportEntryParams) error {
	_, err := q.db.Exec(ctx, createUserImportEntry, arg.ImportID, arg.UserID, arg.Email)
	return err
}

const deleteFinishedUserImportsBefore = `-- name: DeleteFinishedUserImportsBefore :execrows
DELETE FROM user_imports
WHERE state IN ('completed', 'failed') AND finished_at < $1
`

func (q *Queries) DeleteFinishedUserImportsBefore(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedUserImportsBefore, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failUserImportEntry = `-- name: FailUserImportEntry :exec
UPDATE user_import_entries
SET state = 'failed'
WHERE import_id = $1 AND user_id = $2 AND state = 'pending'
`

type FailUserImportEntryParams struct {
	ImportID uuid.UUID `json:"import_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) FailUserImportEntry(ctx context.Context, arg FailUserImportEntryParams) error {
	_, err := q.db.Exec(ctx, failUserImportEntry, arg.ImportID, arg.UserID)
	return err
}

const finishUserImport = `-- name: FinishUserImport :one
WITH counts AS (
    SELECT
        count(*) FILTER (WHERE state = 'completed')::integer AS completed_count,
        count(*) FILTER (WHERE state = 'failed')::integer AS failed_count
    FROM user_import_entries
    WHERE import_id = $1
)
UPDATE user_imports
SET
    state = CASE WHEN counts.failed_count > 0 THEN 'failed'::user_import_state ELSE 'completed'::user_import_state END,
    completed_count = counts.completed_count,
    failed_count = counts.failed_count,
    finished_at = now()
FROM counts
WHERE id = $1
RETURNING user_imports.id, user_imports.state, user_imports.total_count, user_imports.completed_count, user_imports.failed_count, user_imports.created_at, user_imports.started_at, user_imports.finished_at, user_imports.correlation_id
`

func (q *Queries) FinishUserImport(ctx context.Context, id uuid.UUID) (UserImport, error) {
	row := q.db.QueryRow(ctx, finishUserImport, id)
	var i UserImport
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.TotalCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CorrelationID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserImport = `-- name: GetUserImport :one
SELECT id, state, total_count, completed_count, failed_count, created_at, started_at, finished_at, correlation_id
FROM user_imports
WHERE id = $1
`

func (q *Queries) GetUserImport(ctx context.Context, id uuid.UUID) (UserImport, error) {
	row := q.db.QueryRow(ctx, getUserImport, id)
	var i UserImport
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.TotalCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CorrelationID,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :one
SELECT user_id, revision, permissions, updated_at
FROM user_permissions
WHERE user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) (UserPermission, error) {
	row := q.db.QueryRow(ctx, getUserPermissions, userID)
	var i UserPermission
	err := row.Scan(
		&i.UserID,
		&i.Revision,
		&i.Permissions,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingUserImportEntries = `-- name: ListPendingUserImportEntries :many
SELECT entries.import_id, entries.user_id, entries.email, entries.state, imports.correlation_id
FROM user_import_entries AS entries
JOIN user_imports AS imports ON imports.id = entries.import_id
WHERE entries.import_id = $1 AND entries.state = 'pending'
ORDER BY email
`

type ListPendingUserImportEntriesRow struct {
	ImportID      uuid.UUID            `json:"import_id"`
	UserID        uuid.UUID            `json:"user_id"`
	Email         string               `json:"email"`
	State         UserImportEntryState `json:"state"`
	CorrelationID string               `json:"correlation_id"`
}

func (q *Queries) ListPendingUserImportEntries(ctx context.Context, importID uuid.UUID) ([]ListPendingUserImportEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingUserImportEntries, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingUserImportEntriesRow{}
	for rows.Next() {
		var i ListPendingUserImportEntriesRow
		if err := rows.Scan(
			&i.ImportID,
			&i.UserID,
			&i.Email,
			&i.State,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProcessedEvent = `-- name: RecordProcessedEvent :one
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING event_id
`

type RecordProcessedEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) RecordProcessedEvent(ctx context.Context, arg RecordProcessedEventParams) (string, error) {
	row := q.db.QueryRow(ctx, recordProcessedEvent, arg.EventID, arg.EventType)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const startUserImport = `-- name: StartUserImport :one
UPDATE user_imports
SET state = 'running', started_at = COALESCE(started_at, now())
WHERE id = $1 AND state IN ('pending', 'running')
RETURNING id
`

func (q *Queries) StartUserImport(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, startUserImport, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
